version: '3.8'
services:
  blog:
    image: blog_rs:v0.0.1
    env_file: .env  # Load environment variables from .env file
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  nginx:
    image: nginx:alpine
    ports:
      - "8081:8081"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      blog:
        condition: service_healthy
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your@email.com --agree-tos --no-eff-email --force-renewal -d deontevanterpool.com -d www.deontevanterpool.com
    networks:
      - app-network
    # Only run once to initialize certificates
    restart: "no"


networks:
  app-network:
    driver: bridge
