services:
  blog:
    build: .
    env_file: .env
    networks:
      - app-network
    image: 
      ${DOCKER_REGISTRY}/blog:latest

  caddy:
    build: 
      context: .
      dockerfile: Dockerfile.caddy
    image: 
      ${DOCKER_REGISTRY}/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
